name       : gnome-shell
version    : '41.4'
release    : 82
source     :
    - https://download.gnome.org/sources/gnome-shell/41/gnome-shell-41.4.tar.xz : c7eef74af304649c03b86db99bd0bac75a011fbff6774c8ee35583dbcdad8af4
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GNOME Desktop Shell
description: |
    GNOME Shell provides core interface functions like switching windows, launching applications or see your notifications. It takes advantage of the capabilities of modern graphics hardware and introduces innovative user interface concepts to provide a delightful and easy to use experience. GNOME Shell is the defining technology of the GNOME 3 user experience.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gcr-base-3)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-keybindings)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gtk4)
    - pkgconfig(ibus-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libcroco-0.6)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libical)
    - pkgconfig(libmutter-9)
    - pkgconfig(libnma)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(telepathy-glib)
    - pkgconfig(xtst)
    - asciidoc
    - sassc
rundeps    :
    - caribou
    - telepathy-logger
    - gnome-session
    - gnome-session-shell
    - xdg-desktop-portal-gtk
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-Extensions-app-is-hidden-under-Budgie.patch
    %meson_configure -Dtests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
    mv $installdir/etc/xdg $installdir/usr/share/
    rmdir $installdir/etc
