name       : gnome-shell
version    : 3.26.2
release    : 29
source     :
    - https://download.gnome.org/sources/gnome-shell/3.26/gnome-shell-3.26.2.tar.xz : e5a87f2f838d981db9823352b90b2ce2f40d24d31ed9f062dccfa41b820e0b1c
license    : GPL-2.0
component  : desktop.gnome
summary    : GNOME 3 Desktop Shell
description: |
    GNOME Shell provides core interface functions like switching windows, launching applications or see your notifications. It takes advantage of the capabilities of modern graphics hardware and introduces innovative user interface concepts to provide a delightful and easy to use experience. GNOME Shell is the defining technology of the GNOME 3 user experience.
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gcr-base-3)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gnome-keybindings)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libcroco-0.6)
    - pkgconfig(libecal-1.2)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libical)
    - pkgconfig(libmutter-1)
    - pkgconfig(libnm-glib)
    - pkgconfig(libnm-gtk)
    - pkgconfig(libnm-util)
    - pkgconfig(libpulse)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(telepathy-glib)
    - pkgconfig(xtst)
    - docbook-xml
    - sassc
rundeps    :
    - caribou
    - telepathy-logger
    - gnome-session
    - gnome-session-shell
    - xdg-desktop-portal-gtk
setup      : |
    %patch -p1 < $pkgfiles/0001-gdm-Allow-empty-password-text.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
