name       : gnome-shell
version    : 3.20.4
release    : 11
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-shell/3.20/gnome-shell-3.20.4.tar.xz : 0c13eba5ecd3b516538815ab33765ae04bd6faf1549407e81f3bf17b08f2a94d
license    : GPL-2.0
summary    : GNOME 3 Desktop Shell
description: |
    GNOME Shell provides core interface functions like switching windows, launching applications or see your notifications. It takes advantage of the capabilities of modern graphics hardware and introduces innovative user interface concepts to provide a delightful and easy to use experience. GNOME Shell is the defining technology of the GNOME 3 user experience.
component  : desktop.gnome
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(libcroco-0.6)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gjs-internals-1.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(telepathy-glib)
    - pkgconfig(gcr-base-3)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libmutter)
    - pkgconfig(libpulse)
    - pkgconfig(libecal-1.2)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libical)
    - pkgconfig(libsecret-1)
    - pkgconfig(gnome-keybindings)
    - pkgconfig(libnm-gtk)
    - pkgconfig(libnm-glib)
    - pkgconfig(libnm-util)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(x11)
rundeps    :
    - caribou
    - telepathy-logger
    - gnome-session
    - gnome-session-shell
setup      : |
    %configure --disable-static \
               --enable-systemd \
               --enable-networkmanager \
               --disable-man
build      : |
    %make
install    : |
    %make_install
